M48
; DRILL file {KiCad 6.0.4-6f826c9f35~116~ubuntu20.04.1} date Mon 16 May 2022 09:48:48 PM MDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-16T21:48:48-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.4-6f826c9f35~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X82.931Y-72.136
X94.869Y-85.344
T0
M30
