#include <string>

const std::string PROGRAM_NAMES[] = {
    "Acoustic Grand\nPiano",
    "Bright Acoustic\nPiano",
    "Electric Grand\nPiano",
    "Honky-tonk Piano",
    "Electric Piano 1",
    "Electric Piano 2",
    "Harpsichord",
    "Clavinet",
    "Celesta",
    "Glockenspiel",
    "Music Box",
    "Vibraphone",
    "Marimba",
    "Xylophone",
    "Tubular Bells",
    "Dulcimer",
    "Drawbar Organ",
    "Percussive Organ",
    "Rock Organ",
    "Church Organ",
    "Reed Organ",
    "Accordion",
    "Harmonica",
    "Tango Accordion",
    "Nylon Acoustic\nGuitar",
    "Steel Acoustic\nGuitar",
    "Jazz Electric\nGuitar",
    "Clean Electric\nGuitar",
    "Muted Electric\nGuitar",
    "Overdriven\nGuitar",
    "Distortion\nGuitar",
    "Guitar harmonics",
    "Acoustic Bass",
    "Electric Bass\n(finger)",
    "Electric Bass\n(pick)",
    "Fretless Bass",
    "Slap Bass 1",
    "Slap Bass 2",
    "Synth Bass 1",
    "Synth Bass 2",
    "Violin",
    "Viola",
    "Cello",
    "Contrabass",
    "Tremolo Strings",
    "Pizzicato\nStrings",
    "Orchestral Harp",
    "Timpani",
    "String Ensemble\n1",
    "String Ensemble\n2",
    "Synth Strings 1",
    "Synth Strings 2",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Voice",
    "Orchestra Hit",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Muted Trumpet",
    "French Horn",
    "Brass Section",
    "Synth Brass 1",
    "Synth Brass 2",
    "Soprano Sax",
    "Alto Sax",
    "Tenor Sax",
    "Baritone Sax",
    "Oboe",
    "English Horn",
    "Bassoon",
    "Clarinet",
    "Piccolo",
    "Flute",
    "Recorder",
    "Pan Flute",
    "Blown Bottle",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Square Synth\nLead",
    "Sawtooth Synth\nLead",
    "Calliope Synth\nLead ",
    "Chiff Synth Lead",
    "Charang Synth\nLead",
    "Voice Synth Lead",
    "Fifths Synth\nLead",
    "Bass + Synth\nLead",
    "New Age Synth\nPad",
    "Warm Synth Pad",
    "Polysynth Synth\nPad",
    "Choir Synth Pad",
    "Bowed Synth Pad",
    "Metallic Synth\nPad",
    "Halo Synth Pad",
    "Sweep Synth Pad",
    "FX 1\n(rain)",
    "FX 2\n(soundtrack)",
    "FX 3\n(crystal)",
    "FX 4\n(atmosphere)",
    "FX 5\n(brightness)",
    "FX 6\n(goblins)",
    "FX 7\n(echoes)",
    "FX 8\n(sci-fi)",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Kalimba",
    "Bag pipe",
    "Fiddle",
    "Shanai",
    "Tinkle Bell",
    "Agogo",
    "Steel Drums",
    "Woodblock",
    "Taiko Drum",
    "Melodic Tom",
    "Synth Drum",
    "Reverse Cymbal",
    "Guitar Fret\nNoise",
    "Breath Noise",
    "Seashore",
    "Bird Tweet",
    "Telephone Ring",
    "Helicopter",
    "Applause",
    "Gunshot",
};

